# Generated by Django 6.0.3 on 2026-03-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('source_name', models.CharField(help_text="e.g., 'Hacker News' or 'The News API'", max_length=100)),
                ('content_preview', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField()),
                ('unique_id', models.CharField(help_text='Unique identifier from the source API', max_length=255, unique=True)),
                ('ai_summary', models.TextField(blank=True, help_text='Placeholder for future Gemini API summary', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Insight',
                'verbose_name_plural': 'AI Insights',
                'ordering': ['-published_at'],
            },
        ),
    ]
